Repository eProsima/Discovery-Server, pull requests merged in 2024-07, with the labels that each got.

#92 [21230] Fix nightly job and move 2.6.x to weekly CI
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
Labels: ready-to-merge, skip-ci

#94 [21267] Fix weekly CI cron expression
  .github/workflows/weekly-ubuntu-ci.yml
Labels: skip-ci

#93 [21244] Add utils script for type generation
  utils/scripts/update_generated_code_from_idl.sh
Labels: skip-ci

#95 [21301] Remove `WriterProxyData` from public APIs
  include/DiscoveryServerManager.h
  src/DiscoveryServerManager.cpp
Labels: ready-to-merge

#97 [21376] Refactor `TopicDataType`
  examples/HelloWorldExampleDS/HelloWorldPubSubTypes.cxx
  examples/HelloWorldExampleDS/HelloWorldPubSubTypes.hpp
  resources/static_types/HelloWorldPubSubTypes.cxx
  resources/static_types/HelloWorldPubSubTypes.hpp
Labels: ready-to-merge

#98 [21300] Remove `ReaderProxyData` from public APIs
  include/DiscoveryServerManager.h
  src/DiscoveryServerManager.cpp
Labels: ready-to-merge

#101 [21407] Remove example
  CMakeLists.txt
  examples/HelloWorldExampleDS/.gitignore
  examples/HelloWorldExampleDS/CMakeLists.txt
  examples/HelloWorldExampleDS/HelloWorld.hpp
  examples/HelloWorldExampleDS/HelloWorld.idl
  examples/HelloWorldExampleDS/HelloWorldCdrAux.hpp
  examples/HelloWorldExampleDS/HelloWorldCdrAux.ipp
  examples/HelloWorldExampleDS/HelloWorldPubSubTypes.cxx
  examples/HelloWorldExampleDS/HelloWorldPubSubTypes.hpp
  examples/HelloWorldExampleDS/HelloWorldPublisher.cpp
  examples/HelloWorldExampleDS/HelloWorldPublisher.h
  examples/HelloWorldExampleDS/HelloWorldServer.cpp
  examples/HelloWorldExampleDS/HelloWorldServer.h
  examples/HelloWorldExampleDS/HelloWorldSubscriber.cpp
  examples/HelloWorldExampleDS/HelloWorldSubscriber.h
  examples/HelloWorldExampleDS/HelloWorld_main.cpp
  examples/HelloWorldExampleDS/README.txt
  examples/HelloWorldExampleDS/optionparser.h
  resources/xsd/discovery-server.xsd
  utils/scripts/update_generated_code_from_idl.sh
Labels: ci-pending, ready-to-merge

#99 [21295] Participant discovery structures refactor
  include/DiscoveryServerManager.h
  src/DiscoveryServerManager.cpp
Labels: ci-pending
